"""
level_config.py — all tunable generation constants in one place.

Edit this file to tweak difficulty, piece counts, quality thresholds, or
campaign structure without touching the generation/scoring logic.

Imported by generate_levels.py and difficulty.py.
"""

from engine import GRASS, RABBIT, FOX, WOLF, BEAR, DINO

# ── Food chains per tier ───────────────────────────────────────────────────────

TIER_CHAIN = [
    [GRASS, RABBIT, FOX],
    [GRASS, RABBIT, FOX, WOLF],
    [GRASS, RABBIT, FOX, WOLF, BEAR],
    [GRASS, RABBIT, FOX, WOLF, BEAR, DINO],
]

# ── Campaign structure ─────────────────────────────────────────────────────────

LEVELS_PER_TIER = 5

TIER_META = [
    {'label': 'Fox Forest',    'color': '#ff9824', 'chain': 'G->R->F',
     'levels': list(range(0 * LEVELS_PER_TIER, 1 * LEVELS_PER_TIER))},
    {'label': 'Wolf Ridge',    'color': '#8496f0', 'chain': 'G->R->F->W',
     'levels': list(range(1 * LEVELS_PER_TIER, 2 * LEVELS_PER_TIER))},
    {'label': 'Bear Mountain', 'color': '#cd8038', 'chain': 'G->R->F->W->B',
     'levels': list(range(2 * LEVELS_PER_TIER, 3 * LEVELS_PER_TIER))},
    {'label': 'Dino Peak',     'color': '#6ed3c8', 'chain': 'G->R->F->W->B->D',
     'levels': list(range(3 * LEVELS_PER_TIER, 4 * LEVELS_PER_TIER))},
]

# ── Difficulty targets ─────────────────────────────────────────────────────────
# Explicit 40→90 ramp across 20 levels.  Edit individual values to reshape the
# campaign curve; the generator will try to hit each target within the tier band.

TIER_DIFFICULTY_TARGETS = [
    [40, 45, 50, 55, 60],    # Fox Forest:    40–60
    [60, 63, 65, 68, 70],    # Wolf Ridge:    60–70
    [70, 73, 75, 78, 80],    # Bear Mountain: 70–80
    [80, 83, 85, 88, 90],    # Dino Peak:     80–90
]

DIFFICULTY_TARGETS = [t for tier in TIER_DIFFICULTY_TARGETS for t in tier]
TIER_DIFFICULTY_BANDS = [(tier[0], tier[-1]) for tier in TIER_DIFFICULTY_TARGETS]
TOTAL_LEVELS = len(DIFFICULTY_TARGETS)

# ── Per-token count ranges per tier ───────────────────────────────────────────
# Each entry maps token → (min_count, max_count).  min=0 means the token is
# optional.  The generator picks each token's count independently, so boards
# are asymmetric (e.g. 3 rabbits but only 1 fox) rather than mirrored chains.
# The existing solvability and quality gates filter out unplayable combinations.

TIER_PIECE_RANGES = [
    # Tier 0: Fox Forest  (G→R→F)
    {GRASS: (0, 3), RABBIT: (2, 5), FOX: (1, 3)},
    # Tier 1: Wolf Ridge  (G→R→F→W)
    {GRASS: (0, 2), RABBIT: (1, 4), FOX: (1, 3), WOLF: (1, 2)},
    # Tier 2: Bear Mountain  (G→R→F→W→B)
    {GRASS: (0, 2), RABBIT: (1, 3), FOX: (1, 3), WOLF: (1, 2), BEAR: (1, 2)},
    # Tier 3: Dino Peak  (G→R→F→W→B→D)
    # Kept tighter — 12-piece boards already strain the BFS budget.
    {GRASS: (0, 1), RABBIT: (1, 2), FOX: (1, 2), WOLF: (1, 2), BEAR: (1, 2), DINO: (1, 2)},
]

# ── Minimum score targets per tier ────────────────────────────────────────────
# Prevents trivially low objectives.  Values represent the minimum meaningful
# chain completion score for each tier.

MIN_SCORE_BY_TIER = [8, 12, 32, 40]

# ── Quality thresholds per tier ────────────────────────────────────────────────
# (max_cascade_depth, min_agency_ratio, min_board_spread, min_first_move_branching)

QUALITY_THRESHOLDS = {
    0: (3,    0.30, 1.8, 1),   # Fox Forest
    1: (4,    0.25, 2.0, 2),   # Wolf Ridge
    2: (5,    0.20, 2.0, 2),   # Bear Mountain
    3: (999,  0.10, 1.5, 1),   # Dino Peak — long cascade is the intended spectacle
}

# ── Difficulty scoring constants ───────────────────────────────────────────────
# Used by difficulty.py.  Changing these alters measured difficulty for all levels.

MAX_SOLUTIONS     = 50       # cap for solution-count normalisation
MAX_SEARCH_STATES = 1_000_000
MAX_SLACK         = 8        # normaliser for abs_slack term (also hard cap in _tune_budget)
MAX_MIN_MOVES     = 6        # normaliser for planning-depth bonus

# ── Level names ───────────────────────────────────────────────────────────────
# Names are reassigned after difficulty sorting (slot-based).
# Hints are generated by hint_generator.generate_hint() at build time and stay
# with the board they were generated for — they are NOT reassigned after sorting.

LEVEL_NAMES = [
    # Fox Forest (1-5)
    'First Hunt',     'Fox Trail',     'Two Lanes',     'Corner Push',    'Split Meadow',
    # Wolf Ridge (6-10)
    'Wolf Run',       'Ridge Walk',    'Crossing',      'Pressure Zone',  'Dense Forest',
    # Bear Mountain (11-15)
    'Bear Awakens',   'Mountain Pass', 'High Ridge',    'Four Points',    'Bear Crossing',
    # Dino Peak (16-20)
    'Apex Hunt',      'Dino Valley',   'Cliff Edge',    'Summit Climb',   'Final Summit',
]
